"""
    Generates source/ui_font.h: two antialiased proportional fonts for the game
    picker, rasterised from Segoe UI with 4 bits of alpha per pixel.

    Run once; the output is committed. Kept out of the build so the firmware has
    no font dependency.
"""

from PIL import Image, ImageDraw, ImageFont

OUT = r'C:\Users\Guitarek\Documents\MCUXpressoIDE_25.6.136\workspace\psxe_embedded\source\ui_font.h'

FIRST = 32
LAST = 126

FONTS = [
    ('ui_font_body', r'C:\Windows\Fonts\segoeui.ttf', 17),
    ('ui_font_small', r'C:\Windows\Fonts\segoeui.ttf', 13),
    ('ui_font_title', r'C:\Windows\Fonts\segoeuib.ttf', 26),
]


def build(name, path, size):
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()

    glyphs = []
    blob = bytearray()

    for code in range(FIRST, LAST + 1):
        ch = chr(code)

        # rasterise the glyph on its own, tightly cropped
        box = font.getbbox(ch)
        advance = int(round(font.getlength(ch)))

        if box is None or box[2] <= box[0] or box[3] <= box[1]:
            glyphs.append((0, 0, 0, 0, advance, len(blob)))
            continue

        x0, y0, x1, y1 = box
        w = x1 - x0
        h = y1 - y0

        img = Image.new('L', (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255)

        px = img.load()
        offset = len(blob)

        # 4 bits per pixel, two pixels per byte, high nibble first
        for y in range(h):
            row = bytearray()

            for x in range(0, w, 2):
                a0 = px[x, y] >> 4
                a1 = (px[x + 1, y] >> 4) if (x + 1) < w else 0
                row.append((a0 << 4) | a1)

            blob += row

        glyphs.append((w, h, x0, y0, advance, offset))

    return dict(name=name, size=size, ascent=ascent, line=ascent + descent, glyphs=glyphs, blob=bytes(blob))


def emit(fonts):
    out = []
    w = out.append

    w('/*')
    w('    Fonts for the game picker, generated by tools/make_font.py from Segoe UI.')
    w('')
    w('    Each glyph is a tightly cropped alpha bitmap, four bits per pixel, two')
    w('    pixels per byte with the left pixel in the high nibble. `left` and `top`')
    w('    place the bitmap relative to the pen position and the text baseline,')
    w('    `advance` moves the pen on. Codes 32..126 only; anything else prints as a')
    w('    question mark.')
    w('*/')
    w('')
    w('#ifndef PSXE_UI_FONT_H')
    w('#define PSXE_UI_FONT_H')
    w('')
    w('#include <stdint.h>')
    w('')
    w('typedef struct')
    w('{')
    w('    uint8_t width;')
    w('    uint8_t height;')
    w('    int8_t left;')
    w('    int8_t top;')
    w('    uint8_t advance;')
    w('    uint16_t offset;')
    w('} ui_glyph_t;')
    w('')
    w('typedef struct')
    w('{')
    w('    const uint8_t *bitmap;')
    w('    const ui_glyph_t *glyphs;')
    w('    uint8_t first;')
    w('    uint8_t count;')
    w('    uint8_t line_height;')
    w('    uint8_t ascent;')
    w('} ui_font_t;')
    w('')

    for f in fonts:
        w('/* %s: %d px, %d glyphs, %d bytes of bitmap */' % (f['name'], f['size'], len(f['glyphs']), len(f['blob'])))
        w('static const uint8_t %s_bitmap[] = {' % f['name'])

        line = '   '

        for i, b in enumerate(f['blob']):
            line += ' 0x%02x,' % b

            if len(line) > 108:
                w(line)
                line = '   '

        if line.strip():
            w(line)

        w('};')
        w('')
        w('static const ui_glyph_t %s_glyphs[] = {' % f['name'])

        for (gw, gh, left, top, adv, off) in f['glyphs']:
            w('    {%d, %d, %d, %d, %d, %d},' % (gw, gh, left, top, adv, off))

        w('};')
        w('')
        w('static const ui_font_t %s = {' % f['name'])
        w('    %s_bitmap, %s_glyphs, %d, %d, %d, %d,' % (f['name'], f['name'], FIRST, LAST - FIRST + 1,
                                                         f['line'], f['ascent']))
        w('};')
        w('')

    w('#endif')
    w('')

    return chr(10).join(out)


fonts = [build(n, p, s) for (n, p, s) in FONTS]
open(OUT, 'w', encoding='utf-8', newline=chr(10)).write(emit(fonts))

total = sum(len(f['blob']) for f in fonts)
print('ui_font.h written,', total, 'bytes of glyph data')

for f in fonts:
    print('  %-14s %2d px  ascent %2d  line %2d  %5d bytes' % (f['name'], f['size'], f['ascent'], f['line'], len(f['blob'])))
